### ISSUE TITLE
future of this repo

### ISSUE THREAD

**Issue by k-dominik** [ilastik/multiHypothesesTracking#10]
Dear @chaubold,

i noticed that our fork in the ilastik org diverged a bit from your repo. In a way I think it would be best to transfer this repository to the ilastik org, since we still use and maintain it. What do you think? Alternatively we could try to always add our changes upstream here...

Cheers
Dominik

**Comment by chaubold** [comment]
Hey @k-dominik! Sure, sounds good. 

So similar to https://github.com/chaubold/dpct that would mean I add a link to the ilastik-fork of the repo and archive this one here, right?

Greetings from Virginie's BioVision Center Kick-Off Symposium in Zurich (fun coincidence that you're writing while I am seeing the community again after a long time 😄)

**Comment by k-dominik** [comment]
awww now even more sad that I'm not there - would've been so cool to catch up.

How we do it is up to you really. I personally would prefer you transfer the repo to the ilastik org, so it is absolutely obvious that releases coming from us are from the official source. We recently transferred https://github.com/ilastik/ilastiktools to the ilastik org as well. But of course this is up to you. Archiving with a note would also work :)

**Comment by chaubold** [comment]
Sure, I can transfer the repo! I tried it just now but it obviously doesn't want me to do that because there's already a fork at https://github.com/ilastik with the same name. I'll make the contents of "my" repo mirror those of the "ilastik" version, tell you, then you can delete yours and I'll move ownership, ok?

Yeaaaah, would've been awesome to see you again! Next time! 😄

**Comment by k-dominik** [comment]
Hey I renamed our fork, so you could also just transfer :)

**Comment by chaubold** [comment]
Ah, that also works :) Done! But now there's a commit on master that my version of the repo is no longer maintained so... you'll manage to get rid of that commit ;)

Cheers,
Carsten

**Comment by k-dominik** [comment]
thanks a lot @chaubold! I hope we find an opportunity to catch up, soon!
